# Get as many dependencies from official container images as possible so
# Renovate can keep them current for us.
FROM docker.io/golangci/golangci-lint:v2.13.2@sha256:ba07dffad130794ae79ebaa0056809d18c0168f3f846480ffd3eb6c04578b83d as golangci-lint
FROM ghcr.io/hadolint/hadolint:v2.14.0@sha256:27086352fd5e1907ea2b934eb1023f217c5ae087992eb59fde121dce9c9ff21e as hadolint
FROM docker.io/golang:1.26.2-alpine@sha256:f85330846cde1e57ca9ec309382da3b8e6ae3ab943d2739500e08c86393a21b1

# renovate: datasource=repology depName=alpine_3_23/bash versioning=loose
ARG BASH_VERSION="5.3.3-r1"
# renovate: datasource=repology depName=alpine_3_23/gcc versioning=loose
ARG GCC_VERSION="15.2.0-r2"
# renovate: datasource=repology depName=alpine_3_23/git versioning=loose
ARG GIT_VERSION="2.52.0-r0"
# renovate: datasource=repology depName=alpine_3_23/make versioning=loose
ARG MAKE_VERSION="4.4.1-r3"
# renovate: datasource=repology depName=alpine_3_23/musl versioning=loose
ARG MUSL_VERSION="1.2.5-r23"
# renovate: datasource=repology depName=alpine_3_23/musl-dev versioning=loose
ARG MUSL_DEV_VERSION="1.2.5-r23"

RUN apk add --no-cache \
    bash="${BASH_VERSION}" \
    gcc="${GCC_VERSION}" \
    git="${GIT_VERSION}" \
    make="${MAKE_VERSION}" \
    musl="${MUSL_VERSION}" \
    musl-dev="${MUSL_DEV_VERSION}"

COPY --from=hadolint /bin/hadolint /usr/local/bin/
COPY --from=golangci-lint /usr/bin/golangci-lint /usr/local/bin/

CMD ["/bin/bash"]
