---
name: Auto Labeler

"on":
  # pull_request_target event is required for autolabeler to support all PRs
  # including forks
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    name: Auto label pull requests

    runs-on: ubuntu-latest

    steps:
      # yamllint disable-line rule:line-length rule:comments
      - uses: release-drafter/release-drafter/autolabeler@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yaml
